/**********************
* Created by steve6472 (Mirek Jozefek)
* On date: 15. 6. 2018
* Project: SGE2
*
***********************/

package steve6472.sge.main;

import org.lwjgl.glfw.GLFW;

public interface KeyList
{
	int A = GLFW.GLFW_KEY_A;
	int B = GLFW.GLFW_KEY_B;
	int C = GLFW.GLFW_KEY_C;
	int D = GLFW.GLFW_KEY_D;
	int E = GLFW.GLFW_KEY_E;
	int F = GLFW.GLFW_KEY_F;
	int G = GLFW.GLFW_KEY_G;
	int H = GLFW.GLFW_KEY_H;
	int I = GLFW.GLFW_KEY_I;
	int J = GLFW.GLFW_KEY_J;
	int K = GLFW.GLFW_KEY_K;
	int L = GLFW.GLFW_KEY_L;
	int M = GLFW.GLFW_KEY_M;
	int N = GLFW.GLFW_KEY_N;
	int O = GLFW.GLFW_KEY_O;
	int P = GLFW.GLFW_KEY_P;
	int Q = GLFW.GLFW_KEY_Q;
	int R = GLFW.GLFW_KEY_R;
	int S = GLFW.GLFW_KEY_S;
	int T = GLFW.GLFW_KEY_T;
	int U = GLFW.GLFW_KEY_U;
	int V = GLFW.GLFW_KEY_V;
	int W = GLFW.GLFW_KEY_W;
	int X = GLFW.GLFW_KEY_X;
	int Y = GLFW.GLFW_KEY_Y;
	int Z = GLFW.GLFW_KEY_Z;
	int SPACE = GLFW.GLFW_KEY_SPACE;

	int KP_0 = GLFW.GLFW_KEY_KP_0;
	int KP_1 = GLFW.GLFW_KEY_KP_1;
	int KP_2 = GLFW.GLFW_KEY_KP_2;
	int KP_3 = GLFW.GLFW_KEY_KP_3;
	int KP_4 = GLFW.GLFW_KEY_KP_4;
	int KP_5 = GLFW.GLFW_KEY_KP_5;
	int KP_6 = GLFW.GLFW_KEY_KP_6;
	int KP_7 = GLFW.GLFW_KEY_KP_7;
	int KP_8 = GLFW.GLFW_KEY_KP_8;
	int KP_9 = GLFW.GLFW_KEY_KP_9;
	int KP_ENTER = GLFW.GLFW_KEY_KP_ENTER;

	int _0 = GLFW.GLFW_KEY_0;
	int _1 = GLFW.GLFW_KEY_1;
	int _2 = GLFW.GLFW_KEY_2;
	int _3 = GLFW.GLFW_KEY_3;
	int _4 = GLFW.GLFW_KEY_4;
	int _5 = GLFW.GLFW_KEY_5;
	int _6 = GLFW.GLFW_KEY_6;
	int _7 = GLFW.GLFW_KEY_7;
	int _8 = GLFW.GLFW_KEY_8;
	int _9 = GLFW.GLFW_KEY_9;

	int F1 = GLFW.GLFW_KEY_F1;
	int F2 = GLFW.GLFW_KEY_F2;
	int F3 = GLFW.GLFW_KEY_F3;
	int F4 = GLFW.GLFW_KEY_F4;
	int F5 = GLFW.GLFW_KEY_F5;
	int F6 = GLFW.GLFW_KEY_F6;
	int F7 = GLFW.GLFW_KEY_F7;
	int F8 = GLFW.GLFW_KEY_F8;
	int F9 = GLFW.GLFW_KEY_F9;
	int F10 = GLFW.GLFW_KEY_F10;
	int F11 = GLFW.GLFW_KEY_F11;
	int F12 = GLFW.GLFW_KEY_F12;

	int L_SHIFT = GLFW.GLFW_KEY_LEFT_SHIFT;
	int R_SHIFT = GLFW.GLFW_KEY_RIGHT_SHIFT;
	int L_CONTROL = GLFW.GLFW_KEY_LEFT_CONTROL;
	int R_CONTROL = GLFW.GLFW_KEY_RIGHT_CONTROL;
	int L_ALT = GLFW.GLFW_KEY_LEFT_ALT;
	int R_ALT = GLFW.GLFW_KEY_RIGHT_ALT;
	int BACKSPACE = GLFW.GLFW_KEY_BACKSPACE;
	int ENTER = GLFW.GLFW_KEY_ENTER;
	int LEFT = GLFW.GLFW_KEY_LEFT;
	int RIGHT = GLFW.GLFW_KEY_RIGHT;
	int UP = GLFW.GLFW_KEY_UP;
	int DOWN = GLFW.GLFW_KEY_DOWN;
	int TAB = GLFW.GLFW_KEY_TAB;
	int ESCAPE = GLFW.GLFW_KEY_ESCAPE;
	int SLASH = GLFW.GLFW_KEY_SLASH;
	int HOME = GLFW.GLFW_KEY_HOME;
	int END = GLFW.GLFW_KEY_END;
	int DELETE = GLFW.GLFW_KEY_DELETE;

	int M_SHIFT = GLFW.GLFW_MOD_SHIFT;
    int M_CONTROL = GLFW.GLFW_MOD_CONTROL;
    int M_ALT = GLFW.GLFW_MOD_ALT;
    int RELEASE = GLFW.GLFW_RELEASE;
    int PRESS = GLFW.GLFW_PRESS;
    int REPEAT = GLFW.GLFW_REPEAT;

    int LMB = GLFW.GLFW_MOUSE_BUTTON_1;
	int RMB = GLFW.GLFW_MOUSE_BUTTON_2;
	int MMB = GLFW.GLFW_MOUSE_BUTTON_3;
}
